export enum RouteScreenName {
  Welcome = 'Welcome',
  Phrase = 'Phrase',
  Completed = 'Completed',
  Generate = 'Generate',
  RecoverWallet = 'RecoverWallet',
  TestPassword = 'TestPassword',
  ReceiveWallet = 'ReceiveWallet',
  SelectInput = 'SelectInput',
  History = 'History',
  WalletInfo = 'WalletInfo',
  ExploreWallet = 'ExploreWallet',
  BuildWallet = 'BuildWallet',
  SendWallet = 'SendWallet',
  Home = 'Home',
  CoinJoin = 'CoinJoin',
  Settings = 'Settings',
  BuildWalletTransaction = 'BuildWalletTransaction',
  WalletExplorer = 'WalletExplorer',
}
